### PR TITLE
Upgrade lodash

### PR DESCRIPTION
**Pull request by yeun**

### CODE REVIEW

**Comment by foray1010** [comment]
@yeun what is the reason to include `npm` and `lodash` here? I did a quick search in this repo, can't find we are using these dependencies
https://github.com/yeun/open-color/search?q=npm&unscoped_q=npm
https://github.com/yeun/open-color/search?q=lodash&unscoped_q=lodash

the problem of adding them to dependencies is it downloads a LOT of unnecessary dependencies when I develop my app (added ~1400 lines in my yarn.lock)
https://github.com/foray1010/Popup-my-Bookmarks/pull/497/files

**Comment by yeun** [comment]
@sairion Could you check this out?

**Comment by sairion** [comment]
not sure why both deps are added, they are not needed.

**Comment by sairion** [comment]
@foray1010 I removed the dependencies section and until new pkg is pushed, you can rely on older version (which is 1.6.3) if you can manually specify one. Sorry for inconvenience

**Comment by sairion** [comment]
@yeun please tag `1.7.1` via `npm version patch` and publish new pkg

**Pull request merged**
