### PR TITLE
Script for change color hex at once

### PR DESCRIPTION
**Pull request by makepanic**
should fix the majority of #23 

@yeun I don't know if you want to take this approach, but it's basically a small node script that uses http://handlebarsjs.com/ string templates to generate each file.
The list of colors comed from a [json file](https://github.com/makepanic/open-color/blob/e19f6dad131ef8ecaf6e2de3544b916c1feebfa6/open-color.json) that contains names and hex values.

The `.scss` and `config.yml` template isn't 1:1 the same, `.less`, `.styl`and `.css` are generated identically to the current ones.
If 1:1 matching scss and config.yml are required, i could complicate their templates and rebase.

To get this to run one has to `npm install` and `npm run compile-templates`. The second command compiles the templates and writes the output to paths defined in https://github.com/makepanic/open-color/blob/e19f6dad131ef8ecaf6e2de3544b916c1feebfa6/compile-templates.js#L27-L33 . The js code uses some es6 features. I could rewrite into es5 if needed.

What's missing?
- docs/download/open-color_..*.aco
- ~~docs/download/open-color_..*.ase~~ _added in later rebase_
- ~~docs/download/open-color_..*.sketchpalette~~ _added in later rebase_

I can't really find useful specs for these formats 😞

### CODE REVIEW

**Comment by yeun** [comment]
Thanks so much! I'll check it in this weekend :)

**Comment by yeun** [comment]
> What's missing?
> - docs/download/open-color_..*.aco
> - docs/download/open-color_..*.ase
> - docs/download/open-color_..*.sketchpalette
>
>  I can't really find useful specs for these formats 😞

And sorry for that. I skipped a path `asset`. Now it changed correctly.

**Comment by makepanic** [comment]
After some research i think it's possible to generate [binary `.ase` files](http://www.selapa.net/swatches/colors/fileformats.php#adobe_ase) and [binary `.aco` files](https://web.archive.org/web/20060621113737/http://www.duo-creative.com/chrisb/aco/).
`*.sketchpalette` is a plaintext format which allows us to write a handlebars template for it.

I can only check if the `.ase` works correctly, because gpick and aseprite support importing them. 
I haven't found anything on linux that allows to import `.aco` and `.sketchpalette`.

**Comment by yeun** [comment]
Just looked through and tested your PR. Looks good overall! Thanks for your contribution 😄

**Pull request merged**
